typography_spectrum: 0.5109277183655649
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.14267696836031973
  lightness: 0.4748660430777818
  saturation: 0.6481443317607045
  rhythmicContrast: 0.9564413509797305
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5802825880236924
analytics:
  google: null
  facebook: null
  twitter: null
name: clipyoga
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Peaceful savings
purpose: []
